---
title: "forcasting_pop"
author: "Emilio Otero"
date: "2026-04-13"
output: html_document
---

```{r setup, include=FALSE}
source("stat_func.R")
source("pupulation_model.R")
source("thikanov_inv.R")
library(xtable)
library(glmnet)
library(purrr)
library(patchwork)
library(ggplot2)
library(dplyr)
library(knitr)
library(expm)

# read data
# EM ML
iter_only_i <- readRDS("../data/simulations/iter_only_i.rds")
iter_only_u <- readRDS("../data/simulations/iter_only_u.rds")
deconvolved_ml_p_samples_i <- readRDS("../data/simulations/pi_samples_ml_i.rds")
deconvolved_ml_p_samples_u <- readRDS("../data/simulations/pi_samples_ml_u_no_stop.rds")
# Mom 
deconvolved_mom_p_samples_i <- readRDS("../data/simulations/deconvolved_mom_p_samples_i.rds")

# Error
normalized_convolved_sim <- readRDS("../data/simulations/normalized_convolved_sim.rds")

# Oracle 
normalized_truedist_sim <- readRDS("../data/simulations/normalized_truedist_sim.rds")
```


## summarized data 

### population forcast summary
```{r}
true_proj_f <- function(sim_list, L, n_future = 5, summarize = FALSE) {
  
  leslie_powers <- generate_leslie_powers(L, n_future)

  out <- lapply(sim_list, function(model_block) {
    
    lapply(model_block, function(mat) {
      
      mat <- as.matrix(mat)

      proj <- compute_leslie_projection(
        mat,
        leslie_powers,
        n_future
      )

      if (summarize) {
        summary_leslie_proj(proj)
      } else {
        proj
      }
      
    })
  })

  out
}
# 
forecast_years <- 5

true_summary_proj <- true_proj_f(normalized_truedist_sim, L, n_future = forecast_years, summarize = TRUE)
decon_MoM_summary_proj <- leslie_summary_nested(deconvolved_mom_p_samples_i, L, n_future = forecast_years)
convoluted_summary_proj <- leslie_summary_nested(normalized_convolved_sim, L, n_future = forecast_years)
decon_i_summary_proj <- leslie_summary_nested(deconvolved_ml_p_samples_u, L, n_future = forecast_years)
```

```{r}
flatten_results <- function(nested_list, source_name, models, sample_sizes) {
  
  out <- list()
  idx <- 1
  
  for (m in seq_along(models)) {
    for (s in seq_along(sample_sizes)) {
      
      df <- nested_list[[m]][[1]][[s]]  # <- FIX IS HERE
      
      df$model <- models[m]
      df$sample_size <- sample_sizes[s]
      df$source <- source_name
      df$time <- seq_len(nrow(df))
      
      out[[idx]] <- df
      idx <- idx + 1
    }
  }
  
  do.call(rbind, out)
}


df_con <- flatten_results(convoluted_summary_proj, "Naive estimator", c("σ = 1", "σ = 4"), samples)
df_decon_ML <- flatten_results(decon_i_summary_proj, "ML estimator", c("σ = 1", "σ = 4"), samples) 
df_true_dist <- flatten_results(list(true_summary_proj), "true distribution", c("True dist"), samples) 
df_decon_MoM <- flatten_results(decon_MoM_summary_proj, "MoM estimator", c("σ = 1", "σ = 4"), samples) 
combined_df_projection_sum <- do.call(rbind, list(df_con, df_decon_MoM, df_decon_ML, df_true_dist))
combined_df_projection_sum
```




```{r}
df_final <- combined_df_projection_sum %>%
  group_by(sample_size, time) %>%
  mutate(
    true_mean   = mean[source == "true distribution"][1],
    true_median = median[source == "true distribution"][1],
    true_lower  = lower_95[source == "true distribution"][1],
    true_upper  = upper_95[source == "true distribution"][1]
  ) %>%
  ungroup() %>%
  mutate(
    mean_diff   = mean - true_mean,
    median_diff = median - true_median,
    lower_diff  = lower_95 - true_mean,
    upper_diff  = upper_95 - true_mean
  )
df_final <- df_final %>%
  mutate(time = time - 1)
df_final
```











```{r}
plot_df <- df_final %>%
  filter(sample_size %in% c(50, 100, 250,500,1000),
         source != "true distribution")


make_plot <- function(df, m, s) {
  
  df_sub <- df %>%
    filter(model == m,
           sample_size == s,
           source != "true distribution")
  
  ggplot(df_sub, aes(x = time, color = source)) +
    
    geom_hline(yintercept = 0, linetype = "dashed", alpha = 0.5) +
    
    geom_ribbon(aes(ymin = lower_diff, ymax = upper_diff, fill = source),
                alpha = 0.2, color = NA) +
    
    geom_line(aes(y = mean_diff), linewidth = 1, alpha = 1.2) +
    
    geom_line(aes(y = median_diff, linetype = source), linewidth = 0.8) +
    
    labs(
      title = paste("Error Model", m, "| n =", s),
      x = NULL,
      y = NULL,
      color = "Source",
      fill = "Source",
      linetype = "Source"
    ) + 
    scale_color_manual(values = c(
  "Naive estimator" = "gray40",
  "MoM estimator" = "orange",
  "ML estimator" = "blue"
)) +
scale_fill_manual(values = c(
  "Naive estimator" = "gray40",
  "MoM estimator" = "orange",
  "ML estimator" = "blue"
)) +
scale_linetype_manual(values = c(
  "Naive estimator" = "solid",
  "MoM estimator" = "dashed",
  "ML estimator" = "solid"
)) +
    scale_x_continuous(limits = c(0, 5)) +
    theme_minimal()
}
```

```{r}

make_plot(df_final,"σ = 4","1000")
```
```{r}

models <- c("σ = 1", "σ = 4")
sizes  <- c(100, 1000)
plots <- list()

make_panel_figure <- function(s,df, modelsx) {
  
  plots <- list()
  
  for (m in modelsx) {
    plots[[m]] <- make_plot(plot_df, m, s)
  }
  
  # combine A–D into one grid
  wrap_plots(plots, ncol = 2)
}
p5 <- make_panel_figure(100, plot_df,models)
p6 <- make_panel_figure(1000, plot_df, models)
```



```{r}
p5 <- p5 +
  plot_layout(guides = "collect") +
  plot_annotation(
    title = "Total population forcast error",
    tag_levels = "a"
  ) &
  theme(
    legend.position = "bottom"
  )

# ADD GLOBAL AXIS LABELS:

```
```{r}
library(cowplot)
final_plot_p5 <- ggdraw(p5) +
  draw_label("Years", x = 0.5, y = 0, vjust = -0.5, fontface = "plain") +
  draw_label("Percentage deviation from true total population",
             x = 0, y = 0.5, angle = 90, vjust = 1, size = 11
)

final_plot_p5

```
```{r}
p6 <- p6 +
  plot_layout(guides = "collect") +
  plot_annotation(
    title = "Total population forcast error",
    tag_levels = "a"
  ) &
  theme(
    legend.position = "bottom"
  )

# ADD GLOBAL AXIS LABELS:

```
```{r}

final_plot_p6 <- ggdraw(p6) +
  draw_label("Years", x = 0.5, y = 0, vjust = -0.5, fontface = "plain") +
  draw_label("Percentage deviation from true total population",
             x = 0, y = 0.5, angle = 90, vjust = 1, size = 11
)

final_plot_p6
```
# save plots
```{r}
ggsave(
  filename = "../figures/TP_50_samples.pdf",
  plot = final_plot_p5,
  width = 8,
  height = 6
)
ggsave(
  filename = "../figures/TP_1000_samples.pdf",
  plot = final_plot_p6,
  width = 8,
  height = 6
)
```



```{r}
make_plot <- function(df) {
  
  df_sub <- df %>%
    filter(source != "true distribution")
  
  ggplot(df_sub, aes(x = time, color = source)) +
    
    geom_hline(yintercept = 0, linetype = "dashed", alpha = 0.5) +
    
    geom_ribbon(aes(ymin = lower_diff, ymax = upper_diff, fill = source),
                alpha = 0.2, color = NA) +
    
    geom_line(aes(y = mean_diff), linewidth = 1) +
    
    geom_line(aes(y = median_diff, linetype = source), linewidth = 0.8) +
    
    facet_grid(sample_size ~ model) +
    
    labs(
      x = NULL,
      y = NULL,
      color = "Source",
      fill = "Source",
      linetype = "Source"
    ) + 
    
    scale_color_manual(values = c(
      "Naive estimator" = "gray40",
      "MoM estimator" = "orange",
      "ML estimator" = "blue"
    )) +
    
    scale_fill_manual(values = c(
      "Naive estimator" = "gray40",
      "MoM estimator" = "orange",
      "ML estimator" = "blue"
    )) +
    
    scale_linetype_manual(values = c(
      "Naive estimator" = "solid",
      "MoM estimator" = "dashed",
      "EM ML estimator" = "solid"
    )) +
    
    coord_cartesian(xlim = c(0, 5)) +
    theme_minimal()
}
```

```{r}
df_sub <- df_final %>%
  filter(
    source != "true distribution",
    sample_size %in% c(100, 1000)
  )

p6 <- make_plot(df_sub)

final_plot_p6 <- ggdraw(p6) +
  draw_label("Years", x = 0.5, y = -0.5, vjust = -0.5) +
  draw_label("Percentage deviation from true total population",
             x = 0, y = 0.5, angle = 90, vjust = 1, size = 11)

final_plot_p6

ggsave("../figures/forcast_plot.pdf", final_plot_p6,
       width = 14,
       height = 10,
       dpi = 300)
```

